# Generated by Django 5.2.7 on 2025-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_user_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.AlterField(
            model_name='user',
            name='belt_size',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6')], max_length=2, null=True, verbose_name='Tamanho da Faixa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kimono_size',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6')], max_length=2, null=True, verbose_name='Tamanho do Kimono'),
        ),
    ]
