# Generated by Django 5.2.7 on 2025-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_user_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=8, verbose_name='Status'),
        ),
    ]
