# Generated by Django 5.2.7

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_attendancerequest_class_type'),
    ]

    operations = [
    ]
