# Generated by Django 5.2.7

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_add_class_type_field'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Tenta remover o índice/constraint antigo que causou o IntegrityError
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "idx_16499_academia_attendancerequest_student_id_turma_id_attend";',
                    reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "academia_attendancerequest" DROP CONSTRAINT IF EXISTS "idx_16499_academia_attendancerequest_student_id_turma_id_attend";',
                    reverse_sql=migrations.RunSQL.noop
                ),
                # Tenta remover a constraint com o nome padrão do Django, caso exista
                migrations.RunSQL(
                    sql='ALTER TABLE "academia_attendancerequest" DROP CONSTRAINT IF EXISTS "academia_attendancerequest_student_id_turma_id_atte_c5d2b0e8_uniq";',
                    reverse_sql=migrations.RunSQL.noop
                ),
                # Adiciona a nova constraint de unicidade incluindo class_type
                migrations.RunSQL(
                    sql='ALTER TABLE "academia_attendancerequest" ADD CONSTRAINT "academia_attendancerequest_student_id_turma_id_attendance_date_class_type_uniq" UNIQUE ("student_id", "turma_id", "attendance_date", "class_type");',
                    reverse_sql='ALTER TABLE "academia_attendancerequest" DROP CONSTRAINT IF EXISTS "academia_attendancerequest_student_id_turma_id_attendance_date_class_type_uniq";'
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='attendancerequest',
                    unique_together={('student', 'turma', 'attendance_date', 'class_type')},
                ),
            ]
        ),
    ]
