# Generated by Django 5.2.7 on 2026-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='log',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], default='SUCESSO', max_length=10, verbose_name='Status'),
        ),
    ]
