# Generated by Django 5.2.7 on 2026-01-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0016_log_email_log_first_name_log_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='email',
        ),
        migrations.RemoveField(
            model_name='log',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='status',
        ),
    ]
