# Generated by Django 5.2.7 on 2025-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Grupo',
                'verbose_name_plural': 'Regras de Grupos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=80, unique=True)),
                ('keypass', models.CharField(max_length=255)),
                ('access_group', models.CharField(choices=[('ADM', 'Administradores'), ('PRO', 'Professores'), ('STU', 'Alunos')], default='STU', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_belt', models.CharField(blank=True, choices=[('Branca', 'Branca'), ('CinzaBranca', 'Cinza / Branca'), ('Cinza', 'Cinza'), ('CinzaPreta', 'Cinza / Preta'), ('AmarelaBranca', 'Amarela / Branca'), ('Amarela', 'Amarela'), ('AmarelaPreta', 'Amarela / Preta'), ('LaranjaBranca', 'Laranja / Branca'), ('Laranja', 'Laranja'), ('LaranjaPreta', 'Laranja / Preta'), ('VerdeBranca', 'Verde / Branca'), ('Verde', 'Verde'), ('VerdePreta', 'Verde / Preta'), ('Azul', 'Azul'), ('Roxa', 'Roxa'), ('Marrom', 'Marrom'), ('Preta', 'Preta')], max_length=20, null=True)),
                ('current_degree', models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', '1 Grau'), ('2', '2 Graus'), ('3', '3 Graus'), ('4', '4 Graus')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
