# Generated by Django 5.2.7 on 2025-11-18 15:20

import academia.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('KIMONO', 'Kimono'), ('FAIXA', 'Faixa'), ('RASHGUARD', 'Rashguard'), ('TAXA', 'Taxa')], max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('group_role', models.CharField(choices=[('STD', 'Aluno'), ('PRO', 'Professor'), ('ADM', 'Administrador')], default='STD', max_length=3, verbose_name='Perfil')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=academia.models.photo_upload_to, verbose_name='Foto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(choices=[('BRANCA', 'Branca'), ('CINZA_BRANCA', 'Cinza e Branca'), ('CINZA', 'Cinza'), ('CINZA_PRETA', 'Cinza e Preta'), ('AMARELA_BRANCA', 'Amarela e Branca'), ('AMARELA', 'Amarela'), ('AMARELA_PRETA', 'Amarela e Preta'), ('LARANJA_BRANCA', 'Laranja e Branca'), ('LARANJA', 'Laranja'), ('LARANJA_PRETA', 'Laranja e Preta'), ('VERDE_BRANCA', 'Verde e Branca'), ('VERDE', 'Verde'), ('VERDE_PRETA', 'Verde e Preta'), ('AZUL', 'Azul'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], default='BRANCA', max_length=15, verbose_name='Faixa')),
                ('grau', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Grau')),
                ('data_graduacao', models.DateField(blank=True, null=True, verbose_name='Data da Graduação')),
                ('aluno', models.OneToOneField(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='graduacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Graduações',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('APRO', 'Aprovado'), ('CANC', 'Cancelado'), ('REJE', 'Rejeitado'), ('ENTR', 'Aguardando entrega'), ('FINA', 'Finalizado')], default='PEND', max_length=4, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('final_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final')),
                ('aluno', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por', models.ForeignKey(blank=True, limit_choices_to={'group_role__in': ['PRO', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='academia.item')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('professor', models.ForeignKey(limit_choices_to={'group_role__in': ['PRO', 'ADM']}, on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Aula',
                'verbose_name_plural': 'Plano de Aulas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='academia.planoaula')),
            ],
            options={
                'verbose_name': 'Item do Plano de Aula',
                'verbose_name_plural': 'Itens do Plano de Aula',
                'ordering': ['plano', 'data_aula', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('professor', models.ForeignKey(limit_choices_to={'group_role__in': ['PRO', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('FALTAS', 'Menos Faltas'), ('CAMPEONATO', 'Mini-Campeonato'), ('ALUNO_DESTAQUE', 'Aluno Destaque')], max_length=15, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='academia.turma')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='planoaula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='academia.turma'),
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('APRO', 'Aprovado'), ('REJE', 'Rejeitado')], default='PEND', max_length=4, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.turma')),
            ],
            options={
                'verbose_name': 'Solicitação de Turma',
                'verbose_name_plural': 'Solicitações de Turma',
                'unique_together': {('turma', 'aluno')},
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(limit_choices_to={'group_role': 'STD'}, related_name='turmas', through='academia.TurmaAluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PosicaoRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(verbose_name='Posição')),
                ('pontuacao', models.FloatField(default=0, verbose_name='Pontuação')),
                ('aluno', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_ranking', to=settings.AUTH_USER_MODEL)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='academia.ranking')),
            ],
            options={
                'verbose_name': 'Posição no Ranking',
                'verbose_name_plural': 'Posições no Ranking',
                'ordering': ['ranking', 'posicao'],
                'unique_together': {('ranking', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField(verbose_name='Data da Presença')),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('APRO', 'Aprovado'), ('REJE', 'Rejeitado')], default='PEND', max_length=4, verbose_name='Status')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('aluno', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por', models.ForeignKey(blank=True, limit_choices_to={'group_role__in': ['PRO', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='academia.turma')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-data_presenca'],
                'unique_together': {('aluno', 'turma', 'data_presenca')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Data da Presença')),
                ('reason', models.TextField(verbose_name='Motivo da Solicitação')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Aprovado'), ('REJ', 'Rejeitado'), ('CAN', 'Cancelado')], default='PEN', max_length=3, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'group_role__in': ['PRO', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='academia.turma')),
            ],
            options={
                'verbose_name': 'Solicitação de Presença',
                'verbose_name_plural': 'Solicitações de Presença',
                'ordering': ['-attendance_date'],
                'unique_together': {('student', 'turma', 'attendance_date')},
            },
        ),
    ]
