# Generated by Django 5.2.7 on 2025-10-29 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Grupo',
                'verbose_name_plural': 'Regras de Grupos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=11, unique=True)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=80, unique=True)),
                ('keypass', models.CharField(max_length=255)),
                ('access_group', models.CharField(choices=[('ADM', 'Administradores'), ('PRO', 'Professores'), ('STU', 'Alunos')], default='STU', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_belt', models.CharField(blank=True, choices=[('WHITE', 'Branca'), ('GRAY_WHITE', 'Cinza / Branca'), ('GRAY', 'Cinza'), ('GRAY_BLACK', 'Cinza / Preta'), ('YELLOW_WHITE', 'Amarela / Branca'), ('YELLOW', 'Amarela'), ('YELLOW_BLACK', 'Amarela / Preta'), ('ORANGE_WHITE', 'Laranja / Branca'), ('ORANGE', 'Laranja'), ('ORANGE_BLACK', 'Laranja / Preta'), ('GREEN_WHITE', 'Verde / Branca'), ('GREEN', 'Verde'), ('GREEN_BLACK', 'Verde / Preta'), ('BLUE', 'Azul'), ('PURPLE', 'Roxa'), ('BROWN', 'Marrom'), ('BLACK', 'Preta')], max_length=20, null=True)),
                ('current_degree', models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', '1 Grau'), ('2', '2 Graus'), ('3', '3 Graus'), ('4', '4 Graus'), ('5', '5 Graus'), ('6', '6 Graus')], max_length=1, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Turma ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'access_group': 'PRO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.user')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Data da Solicitação')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Aprovado'), ('REJ', 'Rejeitado'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.class', verbose_name='Turma')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'access_group': 'PRO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to='academia.user')),
                ('student', models.ForeignKey(limit_choices_to={'access_group': 'STU'}, on_delete=django.db.models.deletion.CASCADE, to='academia.user')),
            ],
            options={
                'verbose_name': 'Solicitação de Presença',
                'verbose_name_plural': 'Solicitações de Presenças',
                'ordering': ['-attendance_date'],
            },
        ),
    ]
