# Generated by Django 5.2.7 on 2025-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_belt',
            field=models.CharField(choices=[('WHITE', 'Branca'), ('GRAY_WHITE', 'Cinza / Branca'), ('GRAY', 'Cinza'), ('GRAY_BLACK', 'Cinza / Preta'), ('YELLOW_WHITE', 'Amarela / Branca'), ('YELLOW', 'Amarela'), ('YELLOW_BLACK', 'Amarela / Preta'), ('ORANGE_WHITE', 'Laranja / Branca'), ('ORANGE', 'Laranja'), ('ORANGE_BLACK', 'Laranja / Preta'), ('GREEN_WHITE', 'Verde / Branca'), ('GREEN', 'Verde'), ('GREEN_BLACK', 'Verde / Preta'), ('BLUE', 'Azul'), ('PURPLE', 'Roxa'), ('BROWN', 'Marrom'), ('BLACK', 'Preta')], default='WHITE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='current_degree',
            field=models.CharField(choices=[('0', 'Nenhum'), ('1', '1 Grau'), ('2', '2 Graus'), ('3', '3 Graus'), ('4', '4 Graus'), ('5', '5 Graus'), ('6', '6 Graus')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
