# Generated by Django 5.2.7 on 2025-11-07 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Data da Presença')),
                ('reason', models.TextField(verbose_name='Motivo da Solicitação')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Aprovado'), ('REJ', 'Rejeitado'), ('CAN', 'Cancelado')], default='PEN', max_length=3, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'group_role__in': ['PRO', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='academia.turma')),
            ],
            options={
                'verbose_name': 'Solicitação de Presença',
                'verbose_name_plural': 'Solicitações de Presença',
                'ordering': ['-attendance_date'],
                'unique_together': {('student', 'turma', 'attendance_date')},
            },
        ),
    ]
