# Generated by Django 5.2.7 on 2025-11-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_ranking_data_fim_attendancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('KIMONO', 'Kimono'), ('FAIXA', 'Faixa'), ('RASHGUARD', 'Rashguard'), ('TAXA', 'Taxa')], max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='faixa',
            field=models.CharField(choices=[('BRANCA', 'Branca'), ('CINZA_BRANCA', 'Cinza e Branca'), ('CINZA', 'Cinza'), ('CINZA_PRETA', 'Cinza e Preta'), ('AMARELA_BRANCA', 'Amarela e Branca'), ('AMARELA', 'Amarela'), ('AMARELA_PRETA', 'Amarela e Preta'), ('LARANJA_BRANCA', 'Laranja e Branca'), ('LARANJA', 'Laranja'), ('LARANJA_PRETA', 'Laranja e Preta'), ('VERDE_BRANCA', 'Verde e Branca'), ('VERDE', 'Verde'), ('VERDE_PRETA', 'Verde e Preta'), ('AZUL', 'Azul'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], default='BRANCA', max_length=15, verbose_name='Faixa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='academia.item'),
            preserve_default=False,
        ),
    ]
