# Generated by Django 5.2.7 on 2025-11-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_user_belt_size_user_height_user_kimono_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graduacao',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
