# Generated by Django 5.2.7 on 2025-10-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_user_current_belt_alter_user_current_degree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_Role',
        ),
    ]
