# Generated by Django 5.2.7 on 2025-11-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_attendancerequest_notified_graduacao_notified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presenca',
        ),
    ]
