# Generated by Django 5.2.7 on 2025-10-23 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Turma ativa?'),
        ),
        migrations.CreateModel(
            name='AttendenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('attendence_by', models.ForeignKey(blank=True, limit_choices_to={'access_group': 'PRO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendence_by', to='academia.user')),
                ('student', models.ForeignKey(limit_choices_to={'access_group': 'STU'}, on_delete=django.db.models.deletion.CASCADE, to='academia.user')),
            ],
            options={
                'verbose_name': 'Solicitação de Presença',
                'verbose_name_plural': 'Solicitações de Presenças',
            },
        ),
        migrations.CreateModel(
            name='AttendenceAproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(auto_now=True)),
                ('attendence_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.attendencerequest')),
            ],
            options={
                'verbose_name': 'Aprovação de Presença',
                'verbose_name_plural': 'Aprovações de Presenças',
            },
        ),
    ]
