# Generated by Django 5.2.7 on 2025-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_item_remove_pedido_descricao_remove_pedido_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendente'), ('APRO', 'Aprovado'), ('CANC', 'Cancelado'), ('REJE', 'Rejeitado'), ('ENTR', 'Entregue')], default='PEND', max_length=4, verbose_name='Status'),
        ),
    ]
