# Generated by Django 5.2.7 on 2025-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_class_status_attendencerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_degree',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', '1 Grau'), ('2', '2 Graus'), ('3', '3 Graus'), ('4', '4 Graus'), ('5', '5 Graus'), ('6', '6 Graus')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(max_length=11),
        ),
    ]
