# Generated by Django 5.2.7 on 2025-10-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_user_last_graduation_alter_user_current_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_group',
            field=models.CharField(choices=[('ADM', 'Administradores'), ('PRO', 'Professores'), ('STU', 'Alunos'), ('OFF', 'Desativado(a)')], default='STU', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_belt',
            field=models.CharField(choices=[('Branca', 'Branca'), ('CinzaBranca', 'Cinza / Branca'), ('Cinza', 'Cinza'), ('CinzaPreta', 'Cinza / Preta'), ('AmarelaBranca', 'Amarela / Branca'), ('Amarela', 'Amarela'), ('AmarelaPreta', 'Amarela / Preta'), ('LaranjaBranca', 'Laranja / Branca'), ('Laranja', 'Laranja'), ('LaranjaPreta', 'Laranja / Preta'), ('VerdeBranca', 'Verde / Branca'), ('Verde', 'Verde'), ('VerdePreta', 'Verde / Preta'), ('Azul', 'Azul'), ('Roxa', 'Roxa'), ('Marrom', 'Marrom'), ('Preta', 'Preta')], default='Y', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='current_degree',
            field=models.CharField(choices=[('0', 'Nenhum'), ('1', '1 Grau'), ('2', '2 Graus'), ('3', '3 Graus'), ('4', '4 Graus'), ('5', '5 Graus'), ('6', '6 Graus')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
