# Generated by Django 5.2.7 on 2025-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendente'), ('APRO', 'Aprovado'), ('CANC', 'Cancelado'), ('REJE', 'Rejeitado'), ('ENTR', 'Aguardando entrega'), ('FINA', 'Finalizado')], default='PEND', max_length=4, verbose_name='Status'),
        ),
    ]
