# Generated by Django 5.2.4 on 2025-11-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoaula',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Plano de Aula', 'verbose_name_plural': 'Plano de Aulas'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
    ]
