# Generated by Django 5.2.7 on 2025-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_remove_user_active_alter_user_belt_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('KIMONO', 'Kimono'), ('FAIXA', 'Faixa'), ('HASHGUARD', 'Hashguard'), ('TAXA', 'Taxa')], max_length=10),
        ),
    ]
