# Generated by Django 5.2.7 on 2025-12-17 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='faixa',
            field=models.CharField(choices=[('WHITE', 'Branca'), ('GRAY_WHITE', 'Cinza e Branca'), ('GRAY', 'Cinza'), ('GRAY_BLACK', 'Cinza e Preta'), ('YELLOW_WHITE', 'Amarela e Branca'), ('YELLOW', 'Amarela'), ('YELLOW_BLACK', 'Amarela e Preta'), ('ORANGE_WHITE', 'Laranja e Branca'), ('ORANGE', 'Laranja'), ('ORANGE_BLACK', 'Laranja e Preta'), ('GREEN_WHITE', 'Verde e Branca'), ('GREEN', 'Verde'), ('GREEN_BLACK', 'Verde e Preta'), ('BLUE', 'Azul'), ('PURPLE', 'Roxa'), ('BROWN', 'Marrom'), ('BLACK', 'Preta')], default='BRANCA', max_length=15, verbose_name='Faixa'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
