# Generated by Django 5.2.7

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_alter_graduacao_faixa_log'),
    ]

    operations = [
    ]
