# Generated by Django 5.2.7

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_alter_graduacao_faixa_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='class_type',
            field=models.CharField(choices=[('GI', 'Gi'), ('NOGI', 'No-Gi'), ('BOTH', 'Ambas')], default='BOTH', max_length=4, verbose_name='Tipo de Aula'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerequest',
            unique_together={('student', 'turma', 'attendance_date', 'class_type')},
        ),
    ]
