# Generated by Django 5.2.7 on 2026-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], default='SUCESSO', max_length=7, verbose_name='Status'),
        ),
    ]
