# Generated by Django 5.2.7 on 2026-01-31 18:09

import academia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0016_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default_profile.png', null=True, upload_to=academia.models.photo_upload_to, verbose_name='Foto'),
        ),
    ]
