# Generated by Django 5.2.7 on 2026-02-02 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WHITE', '1ª Fase: Faixa Branca'), ('BLUE', '2ª Fase: Faixa Azul'), ('PURPLE', '3ª Fase: Faixa Roxa'), ('BROWN', '4ª Fase: Faixa Marrom'), ('BLACK', '5ª Fase Final: Faixa Preta')], max_length=15, unique=True, verbose_name='Nome da Faixa')),
                ('order', models.IntegerField(help_text='Ordem de progressão da faixa (ex: Branca=1, Azul=2)', unique=True, verbose_name='Ordem')),
                ('color_code', models.CharField(blank=True, help_text='Código hexadecimal da cor da faixa (ex: #FFFFFF)', max_length=7, null=True, verbose_name='Código da Cor')),
                ('is_black_belt', models.BooleanField(default=False, help_text='Indica se esta faixa é uma faixa preta (para graus diferenciados)', verbose_name='É Faixa Preta?')),
                ('image', models.ImageField(blank=True, help_text='Imagem representativa da faixa para exibição no menu', null=True, upload_to='belts/', verbose_name='Imagem da Faixa')),
            ],
            options={
                'verbose_name': 'Fase (Faixa)',
                'verbose_name_plural': 'Fases (Faixas)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurrentGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Grau (Stripe)')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Graduação')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aluno', models.OneToOneField(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='current_graduation', to=settings.AUTH_USER_MODEL)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia.belt', verbose_name='Faixa Atual')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduação Atual',
                'verbose_name_plural': 'Graduações Atuais',
            },
        ),
        migrations.CreateModel(
            name='GraduationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Grau (Stripe)')),
                ('graduation_date', models.DateField(verbose_name='Data da Graduação')),
                ('is_belt_change', models.BooleanField(default=False, help_text='Indica se este registro representa uma troca de faixa ou apenas atribuição de grau.', verbose_name='Troca de Faixa?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('awarded_by', models.ForeignKey(blank=True, limit_choices_to={'group_role__in': ['PRO', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_graduations', to=settings.AUTH_USER_MODEL)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia.belt', verbose_name='Faixa')),
                ('student', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Graduação',
                'verbose_name_plural': 'Históricos de Graduação',
                'ordering': ['-graduation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_graduation_date', models.DateField(verbose_name='Data Antiga da Graduação')),
                ('new_graduation_date', models.DateField(verbose_name='Nova Data da Graduação')),
                ('reason', models.CharField(max_length=50, verbose_name='Motivo da Alteração')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('current_graduation_history_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_change_requests', to='academia.graduationhistory')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'group_role__in': ['PRO', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_graduation_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Graduação',
                'verbose_name_plural': 'Solicitações de Alteração de Graduação',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.DeleteModel(
            name='Graduacao',
        ),
    ]
