# Generated by Django 5.2.7 on 2026-02-02 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_belt_currentgraduation_graduationhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentgraduation',
            name='belt',
        ),
        migrations.RemoveField(
            model_name='graduationhistory',
            name='belt',
        ),
        migrations.RemoveField(
            model_name='currentgraduation',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='currentgraduation',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='graduationhistory',
            name='awarded_by',
        ),
        migrations.RemoveField(
            model_name='graduationhistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='graduationrequest',
            name='current_graduation_history_entry',
        ),
        migrations.RemoveField(
            model_name='graduationrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='graduationrequest',
            name='student',
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(choices=[('WHITE', 'Branca'), ('GRAY_WHITE', 'Cinza e Branca'), ('GRAY', 'Cinza'), ('GRAY_BLACK', 'Cinza e Preta'), ('YELLOW_WHITE', 'Amarela e Branca'), ('YELLOW', 'Amarela'), ('YELLOW_BLACK', 'Amarela e Preta'), ('ORANGE_WHITE', 'Laranja e Branca'), ('ORANGE', 'Laranja'), ('ORANGE_BLACK', 'Laranja e Preta'), ('GREEN_WHITE', 'Verde e Branca'), ('GREEN', 'Verde'), ('GREEN_BLACK', 'Verde e Preta'), ('BLUE', 'Azul'), ('PURPLE', 'Roxa'), ('BROWN', 'Marrom'), ('BLACK', 'Preta')], max_length=20, verbose_name='Faixa')),
                ('grau', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Grau')),
                ('data_graduacao', models.DateField(verbose_name='Data da Graduação')),
                ('notified', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='graduacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Graduações',
                'ordering': ['-data_graduacao'],
            },
        ),
        migrations.DeleteModel(
            name='Belt',
        ),
        migrations.DeleteModel(
            name='CurrentGraduation',
        ),
        migrations.DeleteModel(
            name='GraduationHistory',
        ),
        migrations.DeleteModel(
            name='GraduationRequest',
        ),
    ]
