# Generated by Django 5.2.7 on 2026-02-05 20:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0019_remove_currentgraduation_belt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='grau',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Grau'),
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nova_data', models.DateField(verbose_name='Nova Data')),
                ('motivo_solicitacao', models.CharField(max_length=50, verbose_name='Motivo da Solicitação')),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('APRO', 'Aprovado'), ('REJE', 'Rejeitado')], default='PEND', max_length=4, verbose_name='Status')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('graduacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_alteracao', to='academia.graduacao')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_graduacao_processadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Graduação',
                'verbose_name_plural': 'Solicitações de Alteração de Graduação',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
