# Generated by Django 5.2.7 on 2026-02-06 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0020_alter_graduacao_grau_solicitacaoalteracaograduacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='grau',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Grau'),
        ),
        migrations.DeleteModel(
            name='SolicitacaoAlteracaoGraduacao',
        ),
    ]
