# Generated by Django 5.2.7 on 2026-02-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0021_alter_graduacao_grau_and_more'),
        ('academia', '0023_revert_graduacao_unique_constraint'),
    ]

    operations = [
    ]
