# Generated by Django 5.2.7 on 2026-02-21 19:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0024_merge_20260221_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAlteracaoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nova_faixa', models.CharField(choices=[('WHITE', 'Branca'), ('GRAY_WHITE', 'Cinza e Branca'), ('GRAY', 'Cinza'), ('GRAY_BLACK', 'Cinza e Preta'), ('YELLOW_WHITE', 'Amarela e Branca'), ('YELLOW', 'Amarela'), ('YELLOW_BLACK', 'Amarela e Preta'), ('ORANGE_WHITE', 'Laranja e Branca'), ('ORANGE', 'Laranja'), ('ORANGE_BLACK', 'Laranja e Preta'), ('GREEN_WHITE', 'Verde e Branca'), ('GREEN', 'Verde'), ('GREEN_BLACK', 'Verde e Preta'), ('BLUE', 'Azul'), ('PURPLE', 'Roxa'), ('BROWN', 'Marrom'), ('BLACK', 'Preta')], max_length=20, verbose_name='Nova Faixa')),
                ('novo_grau', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Novo Grau')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('APRO', 'Aprovado'), ('REJE', 'Rejeitado')], default='PEND', max_length=4, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('aluno', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_graduacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração de Graduação',
                'verbose_name_plural': 'Solicitações de Alteração de Graduação',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
