# Generated by Django 5.2.7 on 2026-02-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0025_solicitacaoalteracaograduacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoalteracaograduacao',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='Graduacao',
        ),
        migrations.DeleteModel(
            name='SolicitacaoAlteracaoGraduacao',
        ),
    ]
