# Generated by Django 5.2.7 on 2026-02-21 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0026_remove_solicitacaoalteracaograduacao_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.CharField(choices=[('White', 'Branca'), ('Grey', 'Cinza'), ('Yellow', 'Amarela'), ('Orange', 'Laranja'), ('Green', 'Verde'), ('Blue', 'Azul'), ('Purple', 'Roxa'), ('Brown', 'Marrom'), ('Black', 'Preta'), ('Red', 'Vermelha')], max_length=20, verbose_name='Faixa')),
                ('degree', models.IntegerField(default=0, verbose_name='Grau')),
                ('date', models.DateField(verbose_name='Data da Graduação')),
                ('student', models.ForeignKey(limit_choices_to={'group_role': 'STD'}, on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Graduações',
                'ordering': ['-date'],
                'unique_together': {('student', 'belt', 'degree')},
            },
        ),
    ]
