# Generated by Django 5.2.7 on 2026-02-21 21:41

import academia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0027_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=academia.models.graduation_photo_upload_to, verbose_name='Foto 1'),
        ),
        migrations.AddField(
            model_name='graduation',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=academia.models.graduation_photo_upload_to, verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='graduation',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=academia.models.graduation_photo_upload_to, verbose_name='Foto 3'),
        ),
    ]
