# Generated by Django 5.2.7 on 2026-02-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0024_merge_20260221_1538'),
        ('academia', '0028_graduation_photo1_graduation_photo2_and_more'),
    ]

    operations = [
    ]
