# Generated by Django 5.2.7 on 2026-02-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0029_merge_20260221_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduation',
            unique_together=set(),
        ),
    ]
