# Generated by Django 5.2.7 on 2026-02-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0029_merge_20260222_1533'),
        ('academia', '0030_alter_graduation_unique_together'),
    ]

    operations = [
    ]
