# Generated by Django 5.2.7 on 2026-02-24 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0031_merge_20260223_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actual_belt',
            field=models.CharField(blank=True, choices=[('WHITE', 'Branca'), ('GRAY_WHITE', 'Cinza e Branca'), ('GRAY', 'Cinza'), ('GRAY_BLACK', 'Cinza e Preta'), ('YELLOW_WHITE', 'Amarela e Branca'), ('YELLOW', 'Amarela'), ('YELLOW_BLACK', 'Amarela e Preta'), ('ORANGE_WHITE', 'Laranja e Branca'), ('ORANGE', 'Laranja'), ('ORANGE_BLACK', 'Laranja e Preta'), ('GREEN_WHITE', 'Verde e Branca'), ('GREEN', 'Verde'), ('GREEN_BLACK', 'Verde e Preta'), ('BLUE', 'Azul'), ('PURPLE', 'Roxa'), ('BROWN', 'Marrom'), ('BLACK', 'Preta')], default='WHITE', max_length=20, null=True, verbose_name='Faixa Atual'),
        ),
        migrations.AddField(
            model_name='user',
            name='actual_degree',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Grau Atual'),
        ),
        migrations.AddField(
            model_name='user',
            name='training_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início no Treino'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='belt',
            field=models.CharField(choices=[('WHITE', 'Branca'), ('GRAY_WHITE', 'Cinza e Branca'), ('GRAY', 'Cinza'), ('GRAY_BLACK', 'Cinza e Preta'), ('YELLOW_WHITE', 'Amarela e Branca'), ('YELLOW', 'Amarela'), ('YELLOW_BLACK', 'Amarela e Preta'), ('ORANGE_WHITE', 'Laranja e Branca'), ('ORANGE', 'Laranja'), ('ORANGE_BLACK', 'Laranja e Preta'), ('GREEN_WHITE', 'Verde e Branca'), ('GREEN', 'Verde'), ('GREEN_BLACK', 'Verde e Preta'), ('BLUE', 'Azul'), ('PURPLE', 'Roxa'), ('BROWN', 'Marrom'), ('BLACK', 'Preta')], max_length=20, verbose_name='Faixa'),
        ),
    ]
